name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: docker-wazuh-agent

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Convert repository owner and name to lowercase
      - name: Set lowercase repository path
        run: |
          echo "REPO_PATH_LOWER=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata for tags (only for tagged builds)
      - name: Extract metadata and generate tags (remove 'v' prefix)
        if: startsWith(github.ref, 'refs/tags/v')
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.REPO_PATH_LOWER }}
          tags: |
            type=semver,pattern={{version}}
          flavor: |
            latest=false

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_PATH_LOWER }}/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.REPO_PATH_LOWER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.repository_url }}
